Add PHP 8.0.2, 7.4.15, 7.3.27
php-build/php-build pull request #660
Opened 2021-02-04 13:04 UTC by mumumu

2021-02-04 13:07 UTC, GrahamCampbell requested changes

2021-02-04 13:07 UTC, GrahamCampbell commented on .github/workflows/ci.yml
>          exclude:
Please update the exclude lists.

2021-02-04 13:26 UTC, mumumu commented on .github/workflows/ci.yml
>          exclude:
> Please update the exclude lists.

Should I add 7.0, 7.1, 7.2 which reached EOL?

2021-02-05 00:32 UTC, GrahamCampbell commented on .github/workflows/ci.yml
>          exclude:
That's not what I meant. You need replace all occurrences of `7.3.26` with `7.3.27` in this file, etc. Not just the first ones.

2021-02-05 16:01 UTC, mumumu commented on .github/workflows/ci.yml
>          exclude:
> Not just the first ones.

hmm. Currently, 7.3.x, 7.4.x, 8.0.x are not included in exclude list of ci.yml.

2021-02-06 09:54 UTC, merged

2021-02-06 09:54 UTC, GrahamCampbell commented
Thanks.